// TEST-FIXTURE — KEINE ECHTEN DATEN.
//
// Dies ist eine kleine, frei erfundene (aber schema-konforme) Beispiel-
// Tierliste für Tests von src/quiz/questionGenerator.js und
// src/quiz/difficulty.js. Bewusst NICHT unter data/ abgelegt, um jede
// Verwechslung mit der echten `data/animals.json` aus Issue #2 zu vermeiden
// (siehe Datei-Kommentar in questionGenerator.js für die Begründung, warum
// diese Logik unabhängig von data/animals.json entwickelt/getestet wird).
//
// Format entspricht exakt dem Schema aus docs/workflow/architecture.md,
// Abschnitt "Formales JSON Schema". Der Löwe ist wörtlich der Beispiel-
// datensatz aus der Doku, die übrigen Einträge sind frei erfunden, decken
// aber bewusst verschiedene Kategorien ab sowie Fälle mit fehlenden
// optionalen Feldern (diet, length_cm, lifespan_years, conservation_status,
// name_scientific, fun_fact) — wichtig, um das robuste Überspringen
// fehlender Felder zu testen (siehe architecture.md, "Offene technische
// Fragen", Punkt 2).

export const sampleAnimals = [
  {
    id: "Q140",
    name_de: "Löwe",
    name_scientific: "Panthera leo",
    category: "Säugetier",
    habitat: ["Savanne", "Grasland"],
    continent: ["Afrika"],
    diet: "Fleischfresser",
    weight_kg: 190,
    length_cm: 250,
    lifespan_years: 14,
    conservation_status: "gefährdet",
    fun_fact: "Löwen sind die einzigen Katzen, die in Gruppen (Rudeln) leben.",
  },
  {
    id: "Q7378",
    name_de: "Elefant",
    name_scientific: "Loxodonta africana",
    category: "Säugetier",
    habitat: ["Savanne", "Wald"],
    continent: ["Afrika", "Asien"],
    diet: "Pflanzenfresser",
    weight_kg: 5000,
    length_cm: 400,
    lifespan_years: 60,
    conservation_status: "gefährdet",
  },
  {
    id: "Q29357",
    name_de: "Zebra",
    category: "Säugetier",
    habitat: ["Savanne", "Grasland"],
    continent: ["Afrika"],
    diet: "Pflanzenfresser",
    weight_kg: 350,
    length_cm: 250,
    lifespan_years: 25,
    conservation_status: "nicht gefährdet",
  },
  {
    id: "Q26770",
    name_de: "Giraffe",
    category: "Säugetier",
    habitat: ["Savanne"],
    continent: ["Afrika"],
    diet: "Pflanzenfresser",
    weight_kg: 800,
    length_cm: 500,
    lifespan_years: 25,
    conservation_status: "gefährdet",
  },
  {
    id: "Q19939",
    name_de: "Tiger",
    name_scientific: "Panthera tigris",
    category: "Säugetier",
    habitat: ["Wald", "Dschungel"],
    continent: ["Asien"],
    diet: "Fleischfresser",
    weight_kg: 220,
    length_cm: 300,
    lifespan_years: 20,
    conservation_status: "stark gefährdet",
  },
  {
    id: "Q29572",
    name_de: "Braunbär",
    category: "Säugetier",
    habitat: ["Wald", "Gebirge"],
    continent: ["Europa", "Asien", "Nordamerika"],
    diet: "Allesfresser",
    weight_kg: 300,
    length_cm: 200,
    lifespan_years: 25,
    conservation_status: "nicht gefährdet",
  },
  {
    id: "Q9394",
    name_de: "Pinguin",
    category: "Vogel",
    habitat: ["Ozean", "Küste"],
    continent: ["Antarktis"],
    diet: "Fleischfresser",
    weight_kg: 20,
    // length_cm absichtlich nicht gesetzt (optionales Feld fehlt)
    lifespan_years: 20,
    // conservation_status absichtlich nicht gesetzt
  },
  {
    id: "Q42432",
    name_de: "Papagei",
    category: "Vogel",
    habitat: ["Wald", "Dschungel"],
    continent: ["Südamerika"],
    diet: "Pflanzenfresser",
    weight_kg: 1,
    lifespan_years: 50,
    // conservation_status, length_cm absichtlich nicht gesetzt
  },
  {
    id: "Q2092",
    name_de: "Adler",
    category: "Vogel",
    habitat: ["Gebirge", "Wald"],
    continent: ["Europa", "Nordamerika"],
    diet: "Fleischfresser",
    weight_kg: 6,
    length_cm: 90,
    lifespan_years: 20,
    conservation_status: "nicht gefährdet",
  },
  {
    id: "Q7359",
    name_de: "Krokodil",
    category: "Reptil",
    habitat: ["Süßwasser", "Fluss"],
    continent: ["Afrika"],
    diet: "Fleischfresser",
    weight_kg: 400,
    length_cm: 500,
    lifespan_years: 70,
    conservation_status: "gefährdet",
  },
  {
    id: "Q9253",
    name_de: "Schildkröte",
    category: "Reptil",
    habitat: ["Ozean", "Strand"],
    continent: ["Afrika"],
    diet: "Allesfresser",
    weight_kg: 150,
    length_cm: 100,
    lifespan_years: 80,
    conservation_status: "vom Aussterben bedroht",
  },
  {
    id: "Q3116",
    name_de: "Frosch",
    category: "Amphibie",
    habitat: ["Süßwasser", "Land"],
    continent: ["Europa"],
    diet: "Fleischfresser",
    weight_kg: 0.05,
    // length_cm, lifespan_years, conservation_status absichtlich nicht gesetzt
  },
  {
    id: "Q3130",
    name_de: "Salamander",
    category: "Amphibie",
    habitat: ["Wald", "Süßwasser"],
    continent: ["Europa"],
    diet: "Fleischfresser",
    weight_kg: 0.03,
    length_cm: 15,
    lifespan_years: 15,
    conservation_status: "nicht gefährdet",
  },
  {
    id: "Q3134",
    name_de: "Clownfisch",
    category: "Fisch",
    habitat: ["Ozean", "Riff"],
    continent: ["Australien", "Asien"],
    diet: "Allesfresser",
    weight_kg: 0.03,
    length_cm: 10,
    lifespan_years: 8,
    // conservation_status absichtlich nicht gesetzt
  },
  {
    id: "Q28104",
    name_de: "Weißer Hai",
    name_scientific: "Carcharodon carcharias",
    category: "Fisch",
    habitat: ["Ozean"],
    continent: ["Afrika", "Nordamerika", "Australien"],
    diet: "Fleischfresser",
    weight_kg: 1100,
    length_cm: 600,
    lifespan_years: 30,
    conservation_status: "gefährdet",
  },
  {
    id: "Q7228",
    name_de: "Biene",
    category: "Insekt",
    habitat: ["Wiese", "Garten"],
    continent: ["Europa", "Asien", "Afrika"],
    diet: "Pflanzenfresser",
    weight_kg: 0.0001,
    // length_cm, lifespan_years, conservation_status absichtlich nicht gesetzt
  },
  {
    id: "Q11946",
    name_de: "Schmetterling",
    category: "Insekt",
    habitat: ["Wiese", "Garten"],
    continent: ["Europa"],
    diet: "Pflanzenfresser",
    weight_kg: 0.0005,
    length_cm: 5,
    lifespan_years: 1,
    // conservation_status absichtlich nicht gesetzt
  },
  {
    id: "Q1240",
    name_de: "Vogelspinne",
    category: "Spinnentier",
    habitat: ["Wüste", "Wald"],
    continent: ["Südamerika"],
    diet: "Fleischfresser",
    weight_kg: 0.1,
    length_cm: 10,
    lifespan_years: 15,
    // conservation_status absichtlich nicht gesetzt
  },
  {
    id: "Q37083",
    name_de: "Oktopus",
    name_scientific: "Octopus vulgaris",
    category: "Weichtier",
    habitat: ["Ozean"],
    continent: ["Asien"],
    diet: "Fleischfresser",
    weight_kg: 10,
    length_cm: 60,
    lifespan_years: 2,
    // conservation_status absichtlich nicht gesetzt
  },
  {
    id: "Q1330",
    name_de: "Seestern",
    category: "Sonstiges",
    habitat: ["Ozean"],
    continent: ["Atlantik"],
    weight_kg: 0.5,
    // Nur Pflichtfelder gesetzt: diet, length_cm, lifespan_years,
    // conservation_status, name_scientific, fun_fact absichtlich nicht gesetzt
    // (Randfall: Tier mit ausschließlich Pflichtfeldern).
  },
];
